version: '3.8'
services:
  nodes-development:
    build:
      context: .
      dockerfile: ${FILE_PATH}/nodes.Dockerfile
    image: ${NODES_IMAGE}
    container_name: ${NODES_CONTAINER}
    user: nao
    network_mode: host
    stdin_open: true # docker run -i
    tty: true # docker run -t
    devices:
      - /dev/snd
    volumes:
      - ./src:/home/nao/src
      - ./.env:/home/nao/.env
      - ./share:/home/nao/share
      - ./strugg_letter_data:/home/nao/strugg_letter_data
      - ./credentials:/home/nao/credentials
    command: bash

  frontend-development:
    build:
      context: .
      dockerfile: ${FILE_PATH}/frontend.Dockerfile
    image: ${FRONTEND_IMAGE}
    container_name: ${FRONTEND_CONTAINER}
    volumes:
      - ./src/frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
