name: pr-review
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  review:
    name: ChatGPT code review
    runs-on: ubuntu-latest
    steps:
      - uses: chienpul/chatgpt-pr-review@0.0.1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          files: "*.py"
          logging: "info"